TiendaMor/app/urls.py
from django.urls import path
from app import views
from django.conf import Settings, settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.inicio, name='inicio'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TiendaMor/carro/urls.py
from django.urls import path
from . import views

app_name="carro"

urlpatterns = [
    path('', views.carro, name='carro'),
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
] 

TiendaMor/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('carro/', include('carro.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('registro/', include('registro.urls')),

]

TiendaMor/tienda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tienda, name='tienda'),
    path('categoria/<int:categoria_id>/', views.categoria, name='categoria'),
] 

TiendaMor/tienda/models.py
from django.db import models

# Create your models here.

class CategoriaProducto(models.Model):
    nombre = models.CharField(max_length=50, null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name ='categoria_producto'
        verbose_name_plural ='categorias_producto'

    def __str__(self):
        return self.nombre    

class Producto(models.Model):
    nombre=models.CharField(max_length=50, null=False)
    categorias=models.ForeignKey(CategoriaProducto, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to ='tienda/', null=False, blank=False)
    precio=models.FloatField()
    disponibilidad=models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name ='producto'
        verbose_name_plural ='productos'

    def __str__(self):
        return self.nombre    

TiendaMor/tienda/views.py
from django.core.paginator import Paginator
from django.http.response import Http404
from django.shortcuts import render
from .models import Producto, CategoriaProducto


# Create your views here.

def tienda(request):
    productos = Producto.objects.all()
    categorias = CategoriaProducto.objects.all()
    paginador = Paginator(productos, 6)
    page_number = request.GET.get('page')
    page_obj = paginador.get_page(page_number)

    context = {'productos':productos, 
               'categorias':categorias,
               'productos':page_obj,

    }
    return render(request, 'tienda/tienda.html', context)


def categoria(request, categoria_id):
    categoria = CategoriaProducto.objects.get(id=categoria_id)
    productos = Producto.objects.filter(categorias=categoria)
    return render(request, 'tienda/categoria.html', {'productos':productos,'categoria':categoria,})

TiendaMor/tienda/templates/tienda/categoria.html
{% extends "app/base.html" %}

{% load static %}

{% block content %}
<title>{% block titulo %}Tienda{% endblock %}</title>

<div class="container">
    <div class="row"></div>
    {% for producto in productos %}

    <div class="col-md-3">
        <div class="card" style="width: 100%; margin: 5px 5px;">
            <a href="{{producto.imagen.url}}">
                <img src="{{producto.imagen.url}}" width="200" height="300" class="card-img-top">
            </a>
            <div class="card-body" style="text-align: center;">
                <h7 class="card-title">{{producto.nombre}}</h7>
                <p class="card-text">$ {{producto.precio}}</p>
            </div>

            <div class="card-footer text-center">
                <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al carro</a>
            </div>
        </div>
    </div>


    {% endfor %}
</div>
</div>
{% endblock %}

TiendaMor/tienda/templates/tienda/paginador.html
 <!--Pagination-->
 <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
    {% if productos.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ productos.previous_page_number }}">Previous</a>
      </li>
    {% else %}
        <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
      </li>
    {% endif %}

    {% if productos.number|add:'-4' > 1 %}
        <li class="page-item"><a class="page-link" href="?page={{ productos.number|add:'-5' }}">&hellip;</a></li>
    {% endif %}

    {% for i in productos.paginator.page_range %}
        {% if productos.number == i %}
            <li class="page-item active" aria-current="page">
          <span class="page-link">
            {{ i }}
            <span class="sr-only">(current)</span>
          </span>
        </li>
        {% elif i > productos.number|add:'-5' and i < productos.number|add:'5' %}
             <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
    {% endfor %}

    {% if productos.paginator.num_pages > productos.number|add:'4' %}
       <li class="page-item"><a class="page-link" href="?page={{ productos.number|add:'5' }}">&hellip;</a></li>
    {% endif %}

    {% if productos.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ productos.next_page_number }}">Next</a>
      </li>
    {% else %}
        <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
      </li>
    {% endif %}
  </ul>
</nav>
<!--end of Pagination-->

TiendaMor/tienda/templates/tienda/tienda.html
{% extends "app/base.html" %}

{% load static %}

{% block content %}
<title>{% block titulo %}Tienda{% endblock %}</title>

<div class="container">

 <!-- Categorías -->
    <div style="float:left ; width: auto" class="contenedorFormulario">
        <p style="text-align: center; color: gold;"></p>
        {% for categoria in categorias %}
        <ul>
            <a href="{% url 'categoria' categoria.id %}" 
            class="btn btn-sm btn-success" 
            style="background-color: black; color:  gold; width: 100"
            >{{categoria.nombre}}</a> &nbsp;&nbsp;
        </ul>
        {% endfor %}
    </div>

 <!-- Carrito -->
    <div style="float:right ; width: auto;" class="contenedorFormulario">
        <p style="color: gold;">Ir al Carro</p>
        <a href="{% url 'carro:carro' %}">
            <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'app/img/carrito.jpg' %}" alt=""
                style="width:80px">
        </a>
        <p style="color: gold;">Valor: $ {{importe_total_carro}}</p>
    </div>

 <!-- listado Productos -->
    <div class="row">
        {% for producto in productos %}

        <div class="col-md-3">
            <div class="card" style="width: 100%; margin: 5px 5px;">
                <a href="{{producto.imagen.url}}">
                    <img src="{{producto.imagen.url}}" width="200" height="300" class="card-img-top">
                </a>
                <div class="card-body" style="text-align: center;">
                    <h7 class="card-title">{{producto.nombre}}</h7>
                    <p class="card-text">$ {{producto.precio}}</p>
                </div>

                <div class="card-footer text-center">
                    <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al carro</a>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
<br>
<div>
    {% include 'tienda/paginador.html' %}
</div>
{% endblock %}