TiendaMor/app/urls.py
from django.urls import path
from app import views
from django.conf import Settings, settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.inicio, name='inicio'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TiendaMor/carro/urls.py
from django.urls import path
from . import views

app_name="carro"

urlpatterns = [
    path('', views.carro, name='carro'),
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
] 

TiendaMor/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('carro/', include('carro.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('registro/', include('registro.urls')),

]

TiendaMor/carro/models.py
from django.db import models
from registro.models import Datos

# Create your models here.

class Venta(models.Model):
    cliente=models.ForeignKey(Datos,verbose_name='Cliente', on_delete=models.CASCADE)
    producto=models.CharField(max_length=50,verbose_name='Producto')
    cantidad=models.IntegerField(verbose_name='Cantidad')
    valor_unitario=models.FloatField(verbose_name='Precio')
    valor=models.FloatField(verbose_name='Valor Compra')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name ='venta'
        verbose_name_plural ='ventas'

    def __str__(self):
        return self.producto

TiendaMor/carro/views.py
from django.shortcuts import render, redirect
from .carro import Carro
from tienda.models import Producto

# Create your views here.

def agregar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect('carro:carro')

def eliminar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect('tienda')

def restar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect('carro:carro')

def limpiar_carro(request):
    carro=Carro(request)
    carro.limpiar_carro(carro)
    return redirect('tienda')

def carro(request):
    return render(request, 'carro/carro.html')

TiendaMor/carro/templates/carro/carro.html
{% extends "app/base.html" %}

{% load static %}

{% block content %}
<title>{% block titulo %}Carro{% endblock %}</title>
<div style="float:right ; width: auto;" class="contenedorFormulario">
    <div>
        {% include 'datos/datos.html' %}
    </div>
</div>

<div class="contenedorFormulario">
    <table class="table table-bordered" style="color: gold;">

        <head>
            <th colspan="5" class="text-center">
                Carro Compras
            </th>
            <tr>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Precio</th>
                <th>Valor</th>
                <th>Opción</th>
            </tr>
        </head>

        <tbody>
            {% if request.session.carro.items %}
            <tr colspan="4">
                <div class="alert alert-danger text-center">
                    <a href="{% url 'carro:limpiar' %}" class="btn btn-sm btn-danger">Vaciar</a>
                </div>
            </tr>
            {% for key, value in request.session.carro.items %}
            <tr class="text-center">
                <td>{{value.nombre}}</td>
                <td>{{value.cantidad}}</td>
                <td>$ {{value.valor_unitario}}</td>
                <td>
                    <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                    <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br>
                    $ {{value.precio}}
                </td>
                <td>
                    <a href="{% url 'carro:eliminar' value.producto_id %}" class="btn btn-sm btn-danger">Eliminar</a>
                </td>
            </tr>

            {% endfor %}
            {% else %}
            <tr colspan="4">
                <div class="alert alert-danger text-center">
                    Sin Productos
                </div>
            </tr>
            {% endif %}

</div>

</tbody>


<rfoot>
    <td colspan="5">
        Total: $ {{importe_total_carro}}
    </td>
</rfoot>

</table>


</div>

{% endblock %}